### ISSUE TITLE
Generar anexo mes febrero

### ISSUE THREAD

**Issue by eychamba** [MASTERPC-CIA/bill_anexos#2]
Gernerar el anexo del mes de febrero, con la correccion de los datos. Pide Maria Eugenia

**Comment by jaimejhonle** [comment]
al generar y validar el anexo del mes de febrero presento errores ya que han sido ingresadas facturas de compra del mes de enero en febrero por lo cual debio cambiarse la fecha manualmente, ademas hay errores debido al ingreso de datos con los codigos de sustento, que deben modificar en contabilidad, se envio el anexo a Maria Eugenia para su revision
